title: Xiaodong Hu's Homepage
description: 鲸饮未吞海，剑气已横秋
theme: just-the-docs # modify theme here !!!

url: https://xiaodong-hu.github.io

# aux_links: # remove if you don't want this link to appear on your pages
#   Template Repository: https://github.com/YOUR-USERNAME/YOUR-SITE-NAME

# math: mathjax

markdown: kramdown
